steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/elihealth-test-stripes-gufran/eli-test-scanner-backend',
        '-f',
        'backend/Dockerfile',
        'backend',
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/elihealth-test-stripes-gufran/eli-test-scanner-backend']

images:
  - 'gcr.io/elihealth-test-stripes-gufran/eli-test-scanner-backend'
