export const SIZES = {
  // Heights
  BUTTON_HEIGHT: 40,

  // Paddings
  PADDING_VERTICAL_SMALL: 8,
  PADDING_HORIZONTAL_SMALL: 10,

  // Margins
  MARGIN_HORIZONTAL_MEDIUM: 16,
  MARGIN_VERTICAL_X_SMALL: 5,
  MARGIN_VERTICAL_MEDIUM: 12,

  // Radius
  BORDER_RADIUS_SMALL: 8,
};
